db_path: "./runtime/bot.db"

bot_url: "https://t.me/pocketer_big_bot"

messages:
  responses:
    start: "Здаствуйте! Чтобы сохранить ссылки в своём Pocket аккаунте, для начала вам необходимо придоставить мне доступ. Для этого перейдите по ссылке:\n%s"
    already_authorize: "Вы уже авторизованны! Можете присылать ссылку, а я ее сохраню."
    added_successfully: "Ссылка успешно сохранена!"
    unknown_cmd: "Введена неизветсная комманда!"
  errors:
    default: "Произошла неизвестная ошибка"
    invalid_link: "Это невалидная ссылка!"
    unauthorized : "Вы не авторизированны! Для авторизации используй комаду /start"
    unable_to_add_link: "Упс, что-то пошло не так, я не смог добавить вашу ссылку!"
